# Generated by Django 2.2 on 2020-11-30 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='gpkg_file',
            field=models.FileField(help_text='A GeoPackage file. Each file must less than 1MB ', upload_to='resources/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpkg'])], verbose_name='GeoPackage file'),
        ),
    ]
