# Generated by Django 2.2 on 2020-12-01 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201130_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='gpkg_file',
            field=models.FileField(help_text='A GeoPackage file. The filesize must less than 1MB ', upload_to='resources/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpkg'])], verbose_name='GeoPackage file'),
        ),
        migrations.AlterField(
            model_name='geopackagereview',
            name='geopackage',
            field=models.ForeignKey(help_text='The reviewed GeoPackage', on_delete=django.db.models.deletion.CASCADE, to='resources.Geopackage', verbose_name='GeoPackage'),
        ),
    ]
