# Generated by Django 2.2 on 2020-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201201_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='thumbnail_image',
            field=models.ImageField(help_text='Please upload an image that demonstrate this GeoPackage.', upload_to='resources/%Y', verbose_name='Thumbnail'),
        ),
    ]
