# Generated by Django 2.2 on 2020-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201201_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='name',
            field=models.CharField(help_text='A non-unique name for this GeoPackage.', max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
